server:
  port: 8080
  servlet:
    context-path: /indentity

spring:
  application:
    name: DEMO_MYSQL
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://localhost:3306/ngakezzy?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.mysql.DEMO_MYSQL: DEBUG         # package thực tế của project
    org.springframework.security: DEBUG  # xem chi tiết lỗi 401 từ Spring Security
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  signerKey: "da2f91f33bbc7963ca1fca742b4d58c79729e433e3ce01f838e20a9269be2391"
  valid-duration: 1 # in hours
  refreshable-duration: 120 #in day